version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: dev_requirements.txt
    - method: pip
      path: .

tags:
  - "stable"
  - "latest"
  - "dev"
  - "v*"

submodules:
  include: []
