version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: dev_requirements.txt
    - method: pip
      path: .

submodules:
  include: []

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/conf.py
