# DETR Base Configuration
defaults:
  - config
  - _self_

# Default model is pretrained on MS-COCO
model:
  name: "facebook/detr-resnet-50"
  revision: 'main'

architecture: 'Detr'

train:
  epochs: 40
  lr: 2e-4
  lr_backbone: 2e-5
  optimizer: adamw
  weight_decay: 1e-4
  scheduler:
    type: cosine
    params:
      T_max: 40
      eta_min: 1e-7
