# Allow hyra to inherit from the base,
# then override with this file.
defaults:
  - treeformer
  - _self_

batch_size: 64
workers: 16
accelerator: auto
logs: ./logs/treeformer

train:
    csv_file: /home/veitchmichaelisj/code/DeepForest_jvm/data/neon_train.csv
    root_dir: /home/veitchmichaelisj/code/DeepForest_jvm/data/neon_images

validation:
    csv_file: /home/veitchmichaelisj/code/DeepForest_jvm/data/neon_test.csv
    root_dir: /home/veitchmichaelisj/code/DeepForest_jvm/data/neon_images
