# Allow hyra to inherit from the base,
# then override with this file.
defaults:
  - treeformer
  - _self_

# At full size, bs 32 is the limit on a B200
batch_size: 32
# Higher workers seems to OOM, be careful.
workers: 8
accelerator: auto
