defaults:
  - _self_

# This config has been tested with B200 GPUs. Set cluster CPU RAM to around 32 GB per CPU.
batch_size: 32
workers: 8
accelerator: auto

train:
    csv_file: /blue/ewhite/veitchmichaelisj/deeplidar/output/folds/all_annotations_train_fold_0.csv
    root_dir: /blue/ewhite/veitchmichaelisj/deeplidar/output
    same_size_images: true
    epochs: 40
    scheduler:
        params:
            T_max: 40

validation:
    csv_file: /blue/ewhite/veitchmichaelisj/deeplidar/output/folds/all_annotations_val_fold_0.csv
    root_dir: /blue/ewhite/veitchmichaelisj/deeplidar/output
    same_size_images: true
    distance_threshold: 10.0
