# Allow hyra to inherit from the base,
# then override with this file.
defaults:
  - config
  - _self_

architecture: treeformer

label_dict:
    Tree: 0
num_classes: 1
batch_size: 4
log_root: ./logs/treeformer
model:
    name: ~

train:
    csv_file: /Users/josh/data/Neon_benchmark/train.csv
    root_dir: /Users/josh/data/Neon_benchmark/images
    optimizer: adamw
    lr: 1e-5
    epochs: 60
    scheduler:
        type: cosine
        params:
            T_max: 100
            eta_min: 1e-7
    augmentations:
        - HorizontalFlip:
            p: 0.5
        - VerticalFlip:
            p: 0.5
        - Rotate:
            degrees: 180
            p: 0.5
        - RandomBrightnessContrast:
            brightness: 0.2
            contrast: 0.2
            p: 0.5

# Peak must be >= 30% of max density to count as a predicted tree.
score_thresh: 0.3

validation:
    csv_file: /Users/josh/data/Neon_benchmark/test.csv
    root_dir: /Users/josh/data/Neon_benchmark/images
    val_accuracy_interval: 1

keypoint:
  density_sigma_start: 7.8
  density_sigma_end: 1.6
  mae_weight: 0.025
  count_cls_weight: 0.025
  ot_weight: 0.4
  score_integration_radius: 5
  density_sigma_schedule_epochs: 30
  losses: ~
  norm_cood: true
  log_count_loss: false
  normalize_count_by_area: false
  use_uncertainty_head: false
  uncertainty_delta: 0.2
  uncertainty_mse_weight: 1.0
