---
title: "DataExploration"
author: "Ben Weinstein"
date: "3/7/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = F,message = F)
library(ggplot2)
library(raster)
library(maptools)
library(dplyr)
library(rgdal)
library(stringr)
```

#Task 1

## Ground truth polygons

One file per plot

```{r}
shps<-list.files("/Users/ben/Dropbox/Weecology/ECODSEdataset/Task1/ITC/",pattern=".shp",full.names = T)
itcs<-lapply(shps,readShapePoly)

names(itcs)<-sapply(itcs,function(x){
  id<-unique(x$Plot_ID)
  })
print(names(itcs))
```

## Canopy height model

```{r}
chms<-list.files("/Users/ben/Dropbox/Weecology/ECODSEdataset/RSdata/chm/",pattern=".tif$",full.names = T)
chms<-lapply(chms,raster)

#name the plotids
names(chms)<-sapply(chms,function(x){
    id<-names(x)
    str_match(id,"(\\w+)_chm")[,2]
})
print(names(chms))
```

Let's view a few tree crowns for plots. Only plot if we have matching names.

```{r}
for(x in names(chms)){
  if(!is.null(itcs[[x]])){
    plot(chms[[x]])
    plot(itcs[[x]],add=T)
    title(x)
  }
}
```

# Orthophoto

```{r}
rgb<-list.files("/Users/ben/Dropbox/Weecology/ECODSEdataset/RSdata/camera/",pattern=".tif$",full.names = T)
rgb<-lapply(rgb,stack)

#name the plotids
names(rgb)<-sapply(rgb,function(x){
    id<-names(x[[1]])
    str_match(id,"(\\w+)_camera")[,2]
})


```

Let's view a few tree crowns for RGB images. Only plot if we have matching names.

```{r}
for(x in names(rgb)){
  if(!is.null(itcs[[x]])){
    plotRGB(rgb[[x]])
    plot(itcs[[x]],add=T)
    title(x)
  }
}
```

also overlay the two rasters.


```{r}
for(x in names(rgb)){
  if(!is.null(itcs[[x]])){
    plotRGB(rgb[[x]])
    plot(chms[[x]],add=T,alpha=0.3)
    title(x)
  }
}
```