---
title: "Unsupervised Classification Methods for lidar-based tree crown deliniation"
author: "Ben Weinstein"
date: "4/3/2018"
output: html_document
---

```{r setup, include=FALSE}
library(rgl)
library(diceR)
library(knitr)
knit_hooks$set(webgl = hook_webgl)
library(lidR)
library(ggplot2)
library(raster)
library(reshape2)
library(dplyr)
opts_chunk$set(warning=F,message=F)
source("functions.R")
#load("ITCs.RData")
```

```{r,eval=F}
tile=readLAS("../tests/data/NEON_D03_OSBS_DP1_405000_3276000_classified_point_cloud.laz")

tile<-tile %>% lasfilter(Z < 100)
tile<-tile %>% lasfilter(Z > 0)

#plot(tile, color="Z", colorPalette = heat.colors(50), trim=0.99)

#remove 
summary(tile)
#table(tile@data$Classification)
#ggplot(tile@data,aes(x=as.factor(Classification),y=Z)) + geom_boxplot()
```

```{r,webgl=TRUE}
#Toy file for testing
LASfile <- system.file("extdata", "MixedConifer.laz", package="lidR")
tile = readLAS(LASfile, select = "xyz", filter = "-drop_z_below 0")
col = pastel.colors(200)
knit_hooks$set(webgl = hook_webgl)
plot(tile,backend="rgl")

#add a point index
tile@data$PointID<-1:nrow(tile@data)

#Lastrees updates the cloud inplace, save data in seperate object
ptlist<-list()
```

# Watershed

```{r}
system.time(watershed<-segment_ITC(tile,algorithm = "watershed"))
ptlist[["watershed"]]<-watershed %>% lasfilter(!is.na(treeID)) %>% .@data
```
# Dalponte 2016

```{r}
system.time(dalponte2016<-segment_ITC(tile,algorithm = "dalponte2016"))
ptlist[["dalponte2016"]]<-dalponte2016 %>% lasfilter(!is.na(treeID)) %>% .@data

```

# Silva 2016

```{r}
system.time(silva2016<-segment_ITC(tile,algorithm = "silva2016"))
ptlist[["silva2016"]]<-silva2016 %>% lasfilter(!is.na(treeID)) %>% .@data 
```

#Comparison

## How many tree objects
```{r}
library(pander)
df<-data.frame(Algorthm=c("Watershed","Dalponte2016","Silva2016"),Total_Trees=c( max(ptlist[["watershed"]]$treeID,na.rm=T), max(ptlist[["dalponte2016"]]$treeID,na.rm=T), max(ptlist[["silva2016"]]$treeID,na.rm=T)))
pandoc.table(df,style="rmarkdown")
```

# Consensus

```{r}
pdf<-melt(ptlist,id.vars=colnames(ptlist[["silva2016"]]))
head(pdf)

#Create point ID lookup table
res<-dcast(pdf,PointID~L1,value.var = "treeID")

idframe<-res %>% add_rownames() %>% select(rowname,PointID)
head(res<-res %>% select(-PointID))
```

## Majority Rule

```{r,webgl=TRUE}
system.time(consensus<-majority_voting(res, is.relabelled = FALSE))
#reassign to pointID
consensus_frame<-data.frame(rowname=rownames(res),consensus=consensus) %>% inner_join(idframe) %>% select(PointID,consensus)

#merge with the original tile
tile@data<-merge(tile@data,consensus_frame,all=T)
plot(tile,color="consensus",colorPalette = pastel.colors(100), size = 2)
```

```{r}
save.image("ITCs.RData")
```
